### ISSUE TITLE
.bib file support?

### ISSUE THREAD

**Issue by junoh-moon** [alibaba/block-traces#2]
I used this trace for my paper, and I want to cite this trace. The problem is, I'm not sure about which one should I cite.
So, should I cite this github repository, or "An In-Depth Analysis of Cloud Block Storage Workloads in Large-Scale Production" by J. Li? And can you guys provide a bibtex template for this trace?

**Comment by fallfish** [comment]
You may cite the paper and use the following BibTex. Thanks.
@InProceedings{li20analysis,
  Title={An In-Depth Analysis of Cloud Block Storage Workloads in Large-Scale Production},
  Author={Li, Jinhong and Wang, Qiuping and Lee, Patrick P. C. and Shi, Chao},
  Booktitle={2020 IEEE International Symposium on Workload Characterization (IISWC)},
  Year={2020},
  pages={37-47}
}
