### ISSUE TITLE
The size of one block?

### ISSUE THREAD

**Issue by SoftwareDogZ** [alibaba/block-traces#3]
What's the size of one block in the distributed storage system? Thank you.

**Comment by stepinto** [comment]
These values in offset and length columns from io_traces.csv are in bytes.

**Comment by SoftwareDogZ** [comment]
> These values in offset and length columns from io_traces.csv are in bytes.

Thank you for your reply. But in my question, the "block" means the unit in which the files are stored in the system. For example, one file is separated to several 64M "blocks" in HDFS. So I wanna know the size of one "block" (unit) stored in the alibaba storage system.

**Comment by stepinto** [comment]
Oh I see.  Yes, the backend storage system is distributed, but I cannot talk more into the details.
